from difflib import SequenceMatcher
import os
#d1 = {"graduate": 7, "housing": 11, "uci": 5, "s": 2, "donald": 5, "bren": 9, "school": 8, "of": 6, "information": 6, "and": 8, "computer": 5, "sciences": 3, "home": 2, "about": 2, "the": 7, "dean": 1, "welcome": 1, "facts": 1, "figures": 1, "hall": 2, "visit": 3, "equity": 1, "diversity": 1, "contact": 5, "us": 1, "departments": 1, "science": 1, "informatics": 1, "statistics": 1, "research": 5, "areas": 1, "centers": 1, "highlights": 1, "students": 9, "orientation": 1, "prospective": 2, "how": 2, "to": 6, "apply": 6, "programs": 1, "study": 1, "academic": 6, "year": 4, "plan": 3, "course": 4, "updates": 3, "forms": 2, "policies": 10, "admissions": 2, "faq": 2, "funding": 3, "computing": 3, "support": 3, "campus": 7, "resources": 3, "undergraduate": 2, "advising": 1, "petitions": 1, "ics": 4, "majors": 1, "minors": 1, "integrity": 1, "standing": 1, "enrollment": 1, "coursework": 1, "outside": 1, "grade": 1, "policy": 2, "laptop": 1, "use": 1, "withdrawal": 1, "readmission": 1, "cs": 1, "199": 2, "in4matx": 1, "courses": 1, "graduation": 1, "student": 3, "life": 1, "upcoming": 1, "events": 4, "scholarships": 1, "fellowships": 1, "jobs": 1, "internships": 1, "people": 1, "faculty": 2, "staff": 2, "news": 2, "newsroom": 1, "social": 2, "media": 2, "publications": 1, "get": 1, "involved": 1, "make": 1, "a": 1, "gift": 2, "leadership": 1, "council": 1, "corporate": 1, "partners": 1, "sponsor": 1, "projects": 1, "product": 1, "development": 2, "competition": 1, "alumni": 1, "on": 3, "is": 1, "not": 1, "guaranteed": 1, "all": 1, "looking": 1, "for": 3, "options": 1, "must": 2, "in": 2, "order": 1, "be": 3, "considered": 1, "continuing": 2, "may": 4, "waiting": 1, "list": 1, "at": 1, "any": 1, "time": 1, "during": 1, "admitted": 1, "after": 1, "they": 1, "submit": 1, "their": 1, "statement": 2, "intent": 1, "register": 1, "sir": 1, "do": 1, "so": 1, "by": 2, "1st": 1, "can": 2, "find": 1, "more": 3, "website": 1, "new": 1, "found": 2, "here": 1, "local": 1, "off": 2, "irvine": 4, "athttp": 1, "www": 1, "rental": 1, "living": 1, "com": 1, "if": 1, "you": 1, "have": 1, "transportation": 1, "surrounding": 1, "communities": 1, "such": 1, "as": 1, "costa": 1, "mesa": 1, "santa": 1, "ana": 1, "tustin": 1, "are": 1, "conveniently": 1, "located": 1, "generally": 1, "affordable": 1, "than": 1, "tweets": 1, "ucibrenics": 1, "view": 1, "university": 1, "california": 1, "6210": 1, "ca": 1, "92697": 1, "3425": 1, "homepage": 1, "directory": 1, "employment": 1, "intranet": 1, "kay": 1, "family": 1, "foundation": 1, "lab": 1, "facilities": 1, "map": 1, "directions": 1, "accessibility": 1, "safety": 1, "procedures": 1, "privacy": 1, "coronavirus": 1}
#d2 = {"graduate": 7, "housing": 11, "uci": 5, "s": 2, "donald": 5, "bren": 9, "school": 8, "of": 6, "information": 6, "and": 8, "computer": 5, "sciences": 3, "home": 2, "about": 3, "the": 7, "dean": 1, "welcome": 1, "facts": 1, "figures": 1, "hall": 2, "visit": 3, "equity": 1, "diversity": 1, "contact": 5, "us": 1, "departments": 1, "science": 1, "informatics": 1, "statistics": 1, "research": 5, "areas": 1, "centers": 1, "highlights": 1, "students": 9, "orientation": 1, "prospective": 2, "how": 2, "to": 6, "apply": 6, "programs": 1, "study": 1, "academic": 6, "year": 4, "plan": 3, "course": 4, "updates": 3, "forms": 2, "policies": 10, "admissions": 2, "faq": 2, "funding": 3, "computing": 3, "support": 3, "campus": 7, "resources": 3, "undergraduate": 1, "advising": 1, "petitions": 1, "ics": 4, "majors": 1, "minors": 1, "integrity": 1, "standing": 1, "enrollment": 1, "coursework": 1, "outside": 1, "grade": 1, "policy": 2, "laptop": 1, "use": 1, "withdrawal": 1, "readmission": 1, "cs": 1, "199": 2, "in4matx": 1, "courses": 1, "graduation": 1, "student": 3, "life": 1, "upcoming": 1, "events": 4, "scholarships": 1, "fellowships": 1, "jobs": 1, "internships": 1, "people": 1, "faculty": 2, "staff": 2, "news": 2, "newsroom": 1, "social": 2, "media": 2, "publications": 1, "get": 1, "involved": 1, "make": 1, "a": 1, "gift": 2, "leadership": 1, "council": 1, "corporate": 1, "partners": 1, "sponsor": 1, "projects": 1, "product": 1, "development": 2, "competition": 1, "alumni": 1, "on": 3, "is": 1, "not": 1, "guaranteed": 1, "all": 1, "looking": 1, "for": 3, "options": 1, "must": 2, "in": 2, "order": 1, "be": 3, "considered": 1, "continuing": 2, "may": 4, "waiting": 1, "list": 1, "at": 1, "any": 1, "time": 1, "during": 1, "admitted": 1, "after": 1, "they": 1, "submit": 1, "their": 1, "statement": 2, "intent": 1, "register": 1, "sir": 1, "do": 1, "so": 1, "by": 2, "1st": 1, "can": 2, "find": 1, "more": 3, "website": 1, "new": 1, "found": 2, "here": 1, "local": 1, "off": 2, "irvine": 4, "athttp": 1, "www": 1, "rental": 1, "living": 1, "com": 1, "if": 1, "you": 1, "have": 1, "transportation": 1, "surrounding": 1, "communities": 1, "such": 1, "as": 1, "costa": 1, "mesa": 1, "santa": 1, "ana": 1, "tustin": 1, "are": 1, "conveniently": 1, "located": 1, "generally": 1, "affordable": 1, "than": 1, "tweets": 1, "ucibrenics": 1, "view": 1, "university": 1, "california": 1, "6210": 1, "ca": 1, "92697": 1, "3425": 1, "homepage": 1, "directory": 1, "employment": 1, "intranet": 1, "kay": 1, "family": 1, "foundation": 1, "lab": 1, "facilities": 1, "map": 1, "directions": 1, "accessibility": 1, "safety": 1, "procedures": 1, "privacy": 1, "coronavirus": 1}

r = SequenceMatcher(None, "https://jgarcia.ics.uci.edu/?page_id=65","https://jgarcia.ics.uci.edu/?page_id=295").ratio()
print(r)

    


